name: Init Script Validation

on:
  push:

jobs:
  validate_ubuntu_2204:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: bash ./.init-scripts/ubuntu-22.04.sh
